### ISSUE TITLE
Anticipate that phone numbers will have duplicates

### ISSUE THREAD

**Issue by siruguri** [siruguri/tollmaster#11]
Don't allow non numeric input in phone number field

**Comment by hightechhostel** [comment]
14151234567 and 4151234567 look the same to Twilio so let's also remove any leading 1's from the phone number input.   

Also, Twilio works with international cell phone numbers.  However, they ask that these numbers be proceeded with a "+".   So let's allow the + in the first space.    (Many Nomad-A-What guests may have cell phones from outside the U.S.)  See https://www.twilio.com/help/faq/sms/what-is-global-sms-and-how-does-it-work

**Comment by siruguri** [comment]
I think we should either limit the first version to US numbers, or improve
the interface to allow users to specify the country code separately.

I am inclined to go with the first option because changing the phone number
input interface will take much longer.

Thoughts?

Typed on a mobile device.

**Comment by hightechhostel** [comment]
The interface does not need to be changed.  It already works for international numbers.  The international format is very ubiquitous. My Romanian programmer used the app with +40 123 456 789 and it worked the first tried.  My only point was don't filter out the + because travelers use it already.  Given that we are a travel coworking, we don't want to exclude travelers.

**Comment by siruguri** [comment]
Maybe I'm over-thinking this, but it seems like the logic is going to get hairy if we don't control the interface.

For example, consider: +14152223333, 4152223333 and 14152223333. If the logic is to keep leading +, but remove leading 1s, then the first number will be different from the remaining two.

If we remove leading +1, then are we sure there are no country codes starting with 1? It looks like there are, for example accg to [this list](https://countrycode.org/).

Am I missing something?

**Comment by hightechhostel** [comment]
From a non-programmer perspective this is the way I would deal with phone number inputs: 

1.  *IF* (and only if) left most character is a "+" save it to a variable and strip if off the beginning of the string.  
2.  On the remaining string remove any "1" or "0" form the left most character (throughout the world trunk and international access codes begin with 0 or 1 and are not part of the phone number when calling from the U.S.  If the user has started their number with a 0 or 1 it's incorrect and should be removed. The country code for the U.S. (and various outlying islands) is 1 however, Twilio is based in the U.S. so it will think it' a trunk access code and ignore it).
3. Concatenate the variable set in step 1 to the remaining string.  

Other thoughts: 
I think we can safely assume that only users from outside the U.S. are going to include the "+".  Most American's don't know about this but even if they did know about it, I doubt they would do it while they are within their home country.   

Don't be fooled by the other countries you see on countrycode.org that start with a 1.  Those countries are all using the North American Numbering Plan.  The 3 numbers after the 1 are simply an area code.  If you call from a cell phone you can test this for yourself.  Find a number in Jamaica and call it from a cell phone without the 1.  It will work.

**Comment by siruguri** [comment]
Thanks - this is very helpful!

So how it appears to work out is that if the app were to keep only the
numbers in the input, then ignore leading 1 or 0, then what's left is the
number to use in identifying the user.

What happens when the user _doesn't_ enter a leading +? Is there some
reliable way to identify that a number is in fact international? Or should
we inform users that they should in fact type in a + if they are trying to
use an international number? Because for this to work in Twilio, int'l
numbers have to be prefixed with a + when we communicate with their API.

**Comment by hightechhostel** [comment]
Re: identifying the user - I agree with your methodology.  

Re: user _doesn't_ enter a leading +  -  Yes, I think the easiest solution is to add a note in the phone number entry field.   See attached.  I think that's the best we can do.   If they don't enter the phone number right, there isn't much we can do.  

<img width="493" alt="temp1h-plus-for-international" src="https://cloud.githubusercontent.com/assets/906484/8661325/a33dbb7e-296b-11e5-9aa0-2e83bb45d32c.png">
