### ISSUE TITLE
Request change of background from grey to white

### ISSUE THREAD

**Issue by hightechhostel** [siruguri/tollmaster#21]
Perhaps make CSS a user editable configuration?

**Comment by siruguri** [comment]
User-editable CSS is tough ... we'll have to decide on a color for now. I
think an off-white, like #D5D5D5 is better than pure white.

**Comment by hightechhostel** [comment]
I don't understand why user-editable CSS is tough.  I'm not thinking about any sort of web interface for CSS.   I'm also not thinking you would let the user have control over classes.   I'm only thinking users should be able to modify the relevant stylesheets in /var/www/tollmaster/current/app/assets/stylesheets without fear of them being overwritten by an update.   Is that possible, or still complicated? 

To my eyes, #D5D5D5 is not off-white but more grey.  The feedback I received from people is the current color is too grey. How about #f7f7f7 ?  This seems more like an off-white to my eyes.  Thanks.

**Comment by siruguri** [comment]
I'll put in F7F7F7. I had picked F3F3F3 before I saw this, so we're pretty
close in our "off white" selections :)

If you have a PR implementing "user editable CSS," that'd be a great
feature to add to any app!
