### ISSUE TITLE
CMS not updating text

### ISSUE THREAD

**Issue by hightechhostel** [siruguri/tollmaster#30]
Added CmsConfig #6 with 
Source Symbol = checked_out (same as in en.yml) 
Target text = Checked out!  Please come again.  Check your email for invoice charges. 

This change did not change output.   

I also changed the text in /var/www/tollmaster/current/config/locales/en.yml  and this also did not change output.

**Comment by siruguri** [comment]
You found a place where I forgot to add the db-based config... will push tonight.

**Comment by hightechhostel** [comment]
Thanks, works great now.
