### ISSUE TITLE
Red Background Scared Initial Users

### ISSUE THREAD

**Issue by hightechhostel** [siruguri/tollmaster#31]
The initial users felt the red background mean their connection was not secure and made them hesitate to enter credit card information.   Suggest changing background to white so it looks more like this github page.   

BTW, I tried and was totally unsuccessful to identify this red in the CSS.   I could see the minified CSS was located at application-61458ebe72be54bc892c0460c58b21a9dae902a1913b845699ed3fd4a0e992bb.css but did not see rules related to background color.   

<img width="1422" alt="temp1h-red-background" src="https://cloud.githubusercontent.com/assets/906484/8817931/0b8dbce0-2fef-11e5-8b43-449158a3b579.png">

**Comment by siruguri** [comment]
Ya know what, let's copy from the greats -- I'm going to use the blue/white/gray scheme from Github's pages. Will release tonight.

**Comment by hightechhostel** [comment]
Looks great!   Thanks.
