### ISSUE TITLE
Need Admin Email When User Checks Out

### ISSUE THREAD

**Issue by hightechhostel** [siruguri/tollmaster#33]
Feature Request - Today we had our first customer using the Tollmaster app.  I found myself concerned that the user might checkout before they departed the space.  If they did this I wouldn't know it.   This led me to realize the while the app sends a email upon user checkin, it also needs to send an email to the admin when a user checks out.   This would enable the admin to look around (or check security cameras) to double check and make sure the user has departed.

**Comment by siruguri** [comment]
The To address for this email was not configured in the database, that's why these were not being received. I just added it in the production database.
