### ISSUE TITLE
Make Page 2 More Clear

### ISSUE THREAD

**Issue by hightechhostel** [siruguri/tollmaster#41]
Users think an SMS should be sent every time on page 1 of the app.   They wait and wait for the SMS and do not see they need to reconfirm permission to send an SMS on page 2.  See issue #38. 

Since issue 38 will be a more involved fix, we'd like to see some clearer text on page 2 as a work around.  I have mocked this up below.   Thanks. 
<img width="816" alt="temp1h-send-sms-again" src="https://cloud.githubusercontent.com/assets/906484/11756686/971aa566-a010-11e5-8488-023514bef4af.png">

**Comment by siruguri** [comment]
I deployed a change for this - check it out.
