### ISSUE TITLE
Bug - Text Messages are getting sent twice 

### ISSUE THREAD

**Issue by hightechhostel** [siruguri/tollmaster#43]
After the update Sameer did on Dec 11, text messages are being sent twice.

**Comment by siruguri** [comment]
is this text messages sent to people who ask for the SMS, or who enter phone numbers the first time?

**Comment by hightechhostel** [comment]
Maybe, it was only me.  I had Jeffrey try (who's cell phone was not previously registered) and he only received the message once.   I tried it with both my 150 and 689 (last three numbers) phone numbers and got the message twice.  

UPDATE: I just tested with 689 again and only received the SMS once.   Perhaps it was a temporary Twilio problem.    I'll keep an eye on it.

**Comment by siruguri** [comment]
Did you try it with your numbers by entering them for the first time, or by
asking for a re-send?

**Comment by hightechhostel** [comment]
My numbers asking for a resend.   Although, it stopped sending twice for my
phone ending in 689.  I will test both numbers again tomorrow.

Right now I'm tested the "didn't checkout" problem on  my phone ending in
150.

Jeffrey's number was for the first time and it was fine.

**Comment by siruguri** [comment]
can we close this then?

**Comment by hightechhostel** [comment]
No, it's  still sending the SMS twice.  It seems if the phone number is
already saved in the database, it's sending the SMS twice.

I have tested several times with both of my phone numbers.

**Comment by siruguri** [comment]
found the bug ... fixing.

**Comment by siruguri** [comment]
20e64a77a

**Comment by hightechhostel** [comment]
See attached.

**Comment by hightechhostel** [comment]
Ah crap. Working on it.
